version: "3.7"

services:
  flask:
    build: ./flask
    container_name: flask_app
    restart: always
    expose:
      - 8080
    environment:
      - APP_NAME=TheWebSite
      - DB_NAME=web_proj
      - DB_USER=pyuser
      - DB_PASSWORD=s3cr37
      - DB_HOST=mysql
      - DB_PORT=3306
    volumes:
      - ./flask:/app
  nginx:
    build: ./nginx
    container_name: nginx_server
    restart: always
    ports:
      - "80:80"
  mysql:
    image: mysql:latest
    container_name: mysql_db
    ports:
      - "33010:3306"
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: s3cr37
      MYSQL_DATABASE: web_proj
